# GSL nutrient report figures {#figures}

---
fig_caption: yes
---

```{r, echo=T, eval=T}
	save(site_map,elev_plot,disch_boxplot,disch_ts,mon_inflow,gsl_sal_ts,sal_boxplot_month,gsl_nuts_ts,nuts_boxplot_month,gsl_chl_ts,
		chla_boxplot_month,sal_boxplot_bay,nuts_boxplot_bay,chla_boxplot_bay,wq_map,bs_ts,sal_elev_plot,p_elev_plot,n_elev_plot, jvl_dn_comp,
		tp_lt_ts, tn_lt_ts, chla_lt_ts, salt_lt_ts, tn_mass_plot, fn_mass_plot, tp_mass_plot, fp_mass_plot, salt_mass_plot, chla_mass_plot,
		file='figures-all/figures.RData')
```


```{r, echo=F, fig.cap = "Figure 1. Site location map.", fig.width=8, fig.height=6}
options(warn = -1)
site_map
```
<br>
<br>
<br>

```{r, echo=F, fig.cap = "Figure 2. GSL water surface elevations.", fig.width=8}
elev_plot
```
<br>
<br>
<br>

```{r, echo=F, fig.cap = "Figure 3. Daily discharges at gauged GSL tributaries.", fig.width=8}
disch_boxplot
```
<br>
<br>
<br>

```{r, echo=F, fig.cap = "Figure 4. Daily discharges at gauged GSL tributaries over time.", fig.width=8}
disch_ts
```
<br>
<br>
<br>

```{r, echo=F, fig.cap = "Figure 5. Monthly inflow volumes at gauged GSL tributaries over time.", fig.width=8}
mon_inflow
```
<br>
<br>
<br>

```{r, echo=F, fig.cap = "Figure 6. GSL salinity time series.", fig.width=8}
gsl_sal_ts
```
<br>
<br>
<br>

```{r, echo=F, fig.cap = "Figure 7. GSL monthly variation in salinity.", fig.width=8}
sal_boxplot_month
```
<br>
<br>
<br>

```{r, echo=F, fig.cap = "Figure 8. GSL nutrient concentration and ratio time series.", fig.width=8}
gsl_nuts_ts
```
<br>
<br>
<br>

```{r, echo=F, fig.cap = "Figure 9. GSL monthly variation in nutrient concentrations and ratios.", fig.width=8}
nuts_boxplot_month
```
<br>
<br>
<br>

```{r, echo=F, fig.cap = "Figure 10. GSL chlorophyll a time series.", fig.width=8}
gsl_chl_ts
```
<br>
<br>
<br>

```{r, echo=F, fig.cap = "Figure 11.  GSL monthly variation in chlorophyll a.", fig.width=8}
chla_boxplot_month
```
<br>
<br>
<br>

```{r, echo=F, fig.cap = "Figure 12. Salinity spatial variability, GSL salinity by bay.", fig.width=8}
sal_boxplot_bay
```
<br>
<br>
<br>

```{r, echo=F, fig.cap = "Figure 13.  Nutrient concentration spatial variability, GSL nutrient concentrations and ratios by bay.", fig.width=8}
nuts_boxplot_bay
```
<br>
<br>
<br>

```{r, echo=F, fig.cap = "Figure 14. Chlorophyll a spatial variability, GSL chlorophyll a by bay.", fig.width=8}
chla_boxplot_bay
```
<br>
<br>
<br>

```{r, echo=F, fig.cap = "Figure 15. GSL water quality map: average concentrations and ratios of water quality characteristics at GSL monitoring locations.", fig.width=8, fig.height=6}
wq_map
```
<br>
<br>
<br>

```{r, echo=F, fig.cap = "Figure 16. Ratios of bottom(>= 4m) : surface (<= 1m) sample concentrations of salinity and nutrient constituents.", fig.width=8, fig.height=6}
bs_ts
```
<br>
<br>
<br>

```{r, echo=F, fig.cap = "Figure 17. Surface salinity regression on Gilbert Bay surface elevation.", fig.width=8, fig.height=6}
sal_elev_plot
```
<br>
<br>
<br>

```{r, echo=F, fig.cap = "Figure 18. Surface phosphorus regressions on Gilbert Bay surface elevation.", fig.width=8, fig.height=6}
p_elev_plot
```
<br>
<br>
<br>

```{r, echo=F, fig.cap = "Figure 19. Surface nitrogen regressions on Gilbert Bay surface elevation.", fig.width=8, fig.height=6}
n_elev_plot
```
<br>
<br>
<br>

```{r, echo=F, fig.cap = "Figure 20. Long term total phosphorus pattern.", fig.width=8, fig.height=6}
tp_lt_ts
```
<br>
<br>
<br>

```{r, echo=F, fig.cap = "Figure 21. Long term total nitrogen pattern.", fig.width=8, fig.height=6}
tn_lt_ts
```
<br>
<br>
<br>

```{r, echo=F, fig.cap = "Figure 22. Long term chlorophyll a pattern.", fig.width=8, fig.height=6}
chla_lt_ts
```
<br>
<br>
<br>

```{r, echo=F, fig.cap = "Figure 23. Long term salinity pattern.", fig.width=8, fig.height=6}
salt_lt_ts
```
<br>
<br>
<br>

```{r, echo=F, fig.cap = "Figure 24. JVL vs. Naftz dissolved nitrogen pool estimates.", fig.width=8, fig.height=6}
jvl_dn_comp
```
<br>
<br>
<br>

```{r, echo=F, fig.cap = "Figure 25. Gilbert Bay total nitrogen pool.", fig.width=8, fig.height=6}
tn_mass_plot
```
<br>
<br>
<br>

```{r, echo=F, fig.cap = "Figure 26. Gilbert Bay filtered nitrogen pool.", fig.width=8, fig.height=6}
fn_mass_plot
```
<br>
<br>
<br>

```{r, echo=F, fig.cap = "Figure 27. Gilbert Bay total phosphorus pool.", fig.width=8, fig.height=6}
tp_mass_plot
```
<br>
<br>
<br>

```{r, echo=F, fig.cap = "Figure 28. Gilbert Bay filtered phosphorus pool.", fig.width=8, fig.height=6}
fp_mass_plot
```
<br>
<br>
<br>

```{r, echo=F, fig.cap = "Figure 29. Gilbert Bay salt pool.", fig.width=8, fig.height=6}
salt_mass_plot
```
<br>
<br>
<br>

```{r, echo=F, fig.cap = "Figure 30. Gilbert Bay chlorophyll a pool.", fig.width=8, fig.height=6}
chla_mass_plot
```
<br>
<br>
<br>



