# GSL water quality timeseries {#wq-timeseries}

## Salinity
```{r, echo=F, fig.cap = "GSL salinity time series - all lake sites.", fig.width=8}
gsl_sal_ts
```
<br>
<br>
<br>

```{r, echo=F, fig.cap = "GSL monthly variation in salinity - all lake sites.", fig.width=8}
sal_boxplot_month
```

## Nutrients
```{r, echo=F, fig.cap = "GSL nutrient concentration and ratio time series - all lake sites.", fig.width=8}
gsl_nuts_ts
```
<br>
<br>
<br>

```{r, echo=F, fig.cap = "GSL monthly variation in nutrient concentrations and ratios - all lake sites.", fig.width=8}
nuts_boxplot_month
```

## Chlorophyll a
```{r, echo=F, fig.cap = "GSL chlorophyll a time series - all lake sites.", fig.width=8}
gsl_chl_ts
```
<br>
<br>
<br>

```{r, echo=F, fig.cap = "GSL monthly variation in chlorophyll a - all lake sites.", fig.width=8}
chla_boxplot_month
```
<br>
<br>
<br>

## Bottom:Surface ratio timeseries
```{r, echo=F, fig.cap = "Ratios of bottom(>= 4m) : surface (<= 1m) sample concentrations of salinity and nutrient constituents - all lake sites.", fig.width=8}
bs_ts
```
<br>
<br>
<br>

